name: qrypt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.5
  hexcolor: ^3.0.1
  rxdart: ^0.27.7
  another_flushbar: ^1.12.30
  dio: ^5.4.2
  http: ^1.2.1
  shared_preferences: ^2.2.2
  async: ^2.11.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_keyboard_visibility: ^6.0.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  material_dialogs: ^1.1.3
  jwt_decode_full: ^0.9.2
  dropdown_button2: ^2.3.9


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
